name: "Wait"
description: "Wait a designated number of milliseconds"
inputs:
  token:
    description: "The GitHub authentication token"
    default: ${{ github.token }}
  repository:
    description: "The full name of the target repository."
    default: ${{ github.repository }}
outputs:
  time: # output will be available to future steps
    description: "The message to output"
runs:
  using: "node12"
  main: "dist/index.js"
